import Footer from "@/common/components/layout/footer/footer";
import Header from "@/common/components/layout/header/header";
import ToastProvider from "@/common/context/toastProvider";
import { Roboto_Flex } from "next/font/google";
import "@/styles/globals.scss";

const robotFlex = Roboto_Flex({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  fallback: [["system-ui", "arial"]],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/media/logo/logo.svg" sizes="any" />
      </head>
      <body className={robotFlex.className} suppressHydrationWarning>
        <ToastProvider>
          <Header />
          {children}
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}
